packages:
  - agent
  - app

catalog:
  "@animo-id/eudi-wallet-functionality": 0.0.0-alpha-20260108162340


ignoredBuiltDependencies:
  - es5-ext
  - esbuild
  - sharp

onlyBuiltDependencies:
  - '@2060.io/ffi-napi'
  - '@2060.io/ref-napi'
  - '@biomejs/biome'
  - '@openwallet-foundation/askar-nodejs'