packages:
  - agent
  - app

ignoredBuiltDependencies:
  - es5-ext
  - esbuild
  - sharp

onlyBuiltDependencies:
  - '@2060.io/ffi-napi'
  - '@2060.io/ref-napi'
  - '@biomejs/biome'
  - '@openwallet-foundation/askar-nodejs'
