"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yoUa0S8t4oT
 */
import { TabsTrigger, TabsList, TabsContent, Tabs } from "@/components/ui/tabs";
import { IssueTab } from "./IssueTab";
import { ReceiveTab } from "./ReceiveTab";
import { VerifyTab } from "./VerifyTab";

export function Main() {
  return (
    <>
      <main key="1" className="flex flex-col min-h-screen bg-gray-100">
        <div className="flex items-center justify-between bg-gray-100 w-full p-4">
          <div className="flex items-center">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              alt="Logo"
              className="w-120 h-20"
              height="50"
              src="/logo.svg"
              style={{
                objectFit: "contain",
              }}
              width="200"
            />
          </div>
          <span className="inline-block bg-green-500 text-white text-sm px-2 py-1 rounded-full">
            Playground
          </span>
        </div>
        <div className="flex w-full items-center justify-center">
          <Tabs className="w-full max-w-5xl px-6" defaultValue="issue">
            <TabsList className="grid w-full grid-cols-3">
              <TabsTrigger value="issue">Issue</TabsTrigger>
              <TabsTrigger value="receive">Receive</TabsTrigger>
              <TabsTrigger value="verify">Verify</TabsTrigger>
            </TabsList>
            <TabsContent value="issue">
              <IssueTab />
            </TabsContent>
            <TabsContent value="receive">
              <ReceiveTab />
            </TabsContent>
            <TabsContent value="verify">
              <VerifyTab />
            </TabsContent>
          </Tabs>
        </div>
      </main>
    </>
  );
}
